# -*- coding: utf-8 -*-
"""
/***************************************************************************
 ReservoirCapacityChange
                                 A QGIS plugin
 Lake & Reservoir Capacity Change Estimator is a QGIS plugin designed to estimate the initial and final capacity of lakes and reservoirs, enabling the assessment of capacity change over time. This tool is particularly useful for sedimentation analysis by quantifying storage loss. It generates elevation-capacity and area-elevation graphs and provides volumetric variations at different water levels. Additionally, the plugin includes an optional feature to crop the lake raster using a vector extent layer for more precise analysis.

 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-03-02
        copyright            : (C) 2025 by Sparsh Shekhar
        email                : 22m0587@iitb.ac.in
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

# noinspection PyPep8Naming      
from qgis.core import QgsApplication
from .Reservoir_Capacity_Change_Provider import ReservoirCapacityChangeProvider

def classFactory(iface):
    return ReservoirCapacityChangePlugin()

class ReservoirCapacityChangePlugin:
    def __init__(self):
        self.provider = None

    def initGui(self):
        self.provider = ReservoirCapacityChangeProvider()
        QgsApplication.processingRegistry().addProvider(self.provider)

    def unload(self):
        QgsApplication.processingRegistry().removeProvider(self.provider)