# -*- coding: utf-8 -*-
"""
/***************************************************************************
 ReservoirCapacityChangeDialog
                                 A QGIS plugin
 Lake & Reservoir Capacity Change Estimator is a QGIS plugin designed to estimate the initial and final capacity of lakes and reservoirs, enabling the assessment of capacity change over time. This tool is particularly useful for sedimentation analysis by quantifying storage loss. It generates elevation-capacity and area-elevation graphs and provides volumetric variations at different water levels. Additionally, the plugin includes an optional feature to crop the lake raster using a vector extent layer for more precise analysis.

 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-03-02
        git sha              : $Format:%H$
        copyright            : (C) 2025 by Sparsh Shekhar
        email                : 22m0587@iitb.ac.in
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from qgis.PyQt import uic
from qgis.PyQt import QtWidgets

# This loads your .ui file so that PyQt can populate your plugin with the elements from Qt Designer
FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'Reservoir_Capacity_Change_dialog_base.ui'))


class ReservoirCapacityChangeDialog(QtWidgets.QDialog, FORM_CLASS):
    def __init__(self, parent=None):
        """Constructor."""
        super(ReservoirCapacityChangeDialog, self).__init__(parent)
        # Set up the user interface from Designer through FORM_CLASS.
        # After self.setupUi() you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://qt-project.org/doc/qt-4.8/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.setupUi(self)
