# -*- coding: utf-8 -*-
"""
/***************************************************************************
 ReservoirCapacityChange
                                 A QGIS plugin
 Lake & Reservoir Capacity Change Estimator is a QGIS plugin designed to estimate the initial and final capacity of lakes and reservoirs, enabling the assessment of capacity change over time. This tool is particularly useful for sedimentation analysis by quantifying storage loss. It generates elevation-capacity and area-elevation graphs and provides volumetric variations at different water levels. Additionally, the plugin includes an optional feature to crop the lake raster using a vector extent layer for more precise analysis.

 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2025-03-02
        git sha              : $Format:%H$
        copyright            : (C) 2025 by Sparsh Shekhar
        email                : 22m0587@iitb.ac.in
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
import os
from qgis.core import QgsProcessingProvider, QgsApplication
from qgis.PyQt.QtGui import QIcon
from .Reservoir_Capacity_Change import ReservoirCapacityChange


class ReservoirCapacityChangeProvider(QgsProcessingProvider):
    def __init__(self):
        super().__init__()

    def loadAlgorithms(self):
        self.addAlgorithm(ReservoirCapacityChange())

    def id(self):
        return 'reservoir_capacity_change_estimator'

    def name(self):
        return self.tr('Lake & Reservoir Capacity Change Estimator')

    def longName(self):
        return self.name()

    def icon(self):
        return QIcon(os.path.join(os.path.dirname(__file__), "icon.png"))
